---
title: "dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
  runtime: shiny
---

```{r setup, include=FALSE}
library("flexdashboard")
library("shiny")
library("dplyr")
library("rgdal")
library("rgeos")
library("maptools")
library("ggplot2")
library("stringr")
library("gpclib")
library("mapproj")
library("leaflet")
library("scales")
library("magrittr")
source("datatable_generation.R")
```

```{r data}
data_pop <- get_pop_data()
data_pop_revenus <- get_pop_wage_data(precision="DEP", pop_data=data_pop)
#data_pop_revenus_COM <- get_pop_wage_data(precision="COM", pop_data = data_pop)
data_revenus <- get_wage_data(precision="DEP") %>% rename(DEP=CODGEO)
labels_revenus <- get_wage_labels()
revenus_categories <- colnames(data_pop_revenus)[77:100]
population_categories <- colnames(data_pop[13:84])

#Maps :
#get vestorial file
dept <- readOGR("datas/dpt/DEPARTEMENT.shp", layer= "DEPARTEMENT", verbose=FALSE)

#fit it into a dataframe to merge values to show on map
dept.df <- fortify(spTransform(dept, CRS("+proj=longlat +datum=WGS84")),region="CODE_DEPT")


#Map interactive
dept.interactive=spTransform(dept, CRS("+proj=longlat +datum=WGS84"))

#Données sur les communes trop grosses pour afficher sur des cartes (performances exécrables)

#coms <- readOGR("datas/communes/COMMUNE.shp", layer= "COMMUNE", verbose=FALSE)
#coms.df <- fortify(spTransform(coms, CRS("+proj=longlat +datum=WGS84")),region="INSEE_COM")
#coms.interactive=spTransform(coms, CRS("+proj=longlat +datum=WGS84"))
```


# Exploration

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
  selectInput("revenu_cat", label="Sélection de la catégorie de revenu", choices=revenus_categories)
```


Column
-----------------------------------------------------------------------

### Cartes des revenus par region

```{r}

dept.df2<-merge(data_revenus, dept.df, by.x="DEP", by.y="id")

#plot the map
renderPlot({ggplot() +
  geom_polygon(data = dept.df2, 
               aes(x = long, y = lat, group = group, fill = .data[[input$revenu_cat]]),
               color = "black") + 
  coord_map() +
  scale_fill_gradient(high="#ffa600", low="#2f4b7c")+
  guides(fill = guide_legend(title=input$revenu_cat,reverse = TRUE))+
  theme_void()
})
```

### Carte des revenus par région

```{r}
dept.interactive= sp::merge(dept.interactive, data_revenus,by.x="CODE_DEPT",by.y="DEP")
renderLeaflet({
  
  pal<-colorNumeric(palette = c("#003f5c","white","#ffa600"), domain=(dept.interactive %>% extract2(input$revenu_cat)))
  
  popup_info <- paste0("<strong>Departement: </strong>", 
                    dept.interactive$NOM_DEPT," - ", dept.interactive$CODE_DEPT,
                    "<br><strong>",input$revenu_cat,":  </strong>",
                    round(dept.interactive %>% extract2(input$revenu_cat), digits=2))
  
  leaflet(data = dept.interactive) %>%
  addTiles() %>%
  addPolygons(fillColor = pal(magrittr::extract2(dept.interactive, input$revenu_cat)) ,
              fillOpacity=0.8,
              color = "Black", 
              weight = 1,
              stroke = TRUE,
              popup=popup_info)
})
```

### Revenus par communes

```{r}
# Affecte la performance de façon excessive 
# coms.interactive= sp::merge(coms.interactive, data_pop_revenus_COM[which(data_pop_revenus_COM$annee==2015),],by.x="INSEE_COM",by.y="COM")
# 
# renderLeaflet({
# 
#   pal<-colorNumeric(palette = c("#003f5c","white","#ffa600"), domain=(coms.interactive %>% extract2(input$revenu_cat)))
# 
#   popup_info <- paste0("<strong>Commune: </strong>",
#                     coms.interactive$NOM_DEPT," - ", coms.interactive$CODE_COM,
#                     "<br><strong>",input$revenu_cat,":  </strong>",
#                     round(coms.interactive %>% extract2(input$revenu_cat), digits=2))
# 
#   leaflet(data = coms.interactive) %>%
#   addTiles() %>%
#   addPolygons(fillColor = pal(magrittr::extract2(coms.interactive, input$revenu_cat)) ,
#               fillOpacity=0.8,
#               color = "Black",
#               weight = 1,
#               stroke = TRUE,
#               popup=popup_info)
# })
```


# Population

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("pop_cat", label="Sélection de la catégorie de population", choices=population_categories)
selectInput("annee_sel", label="Sélection de la catégorie de l'année", choices=c("2015","2016","2017"))
```


Row
-----------------------------------------------------------------------

### Carte de la population

```{r}
renderPlot({ggplot() +
  geom_polygon(data = merge(data_pop_revenus[which(data_pop_revenus$annee==input$annee_sel),], dept.df, by.x="DEP", by.y="id"), 
               aes(x = long, y = lat, group = group, fill = .data[[input$pop_cat]]),
               color = "black") + 
  coord_map() +
  scale_fill_gradient(low="#003f5c",high="#d45087")+
  guides(fill = guide_legend(title=input$pop_cat,reverse = TRUE))+
  theme_void()
})
```

### Carte population intéractive

```{r}
#Code ignoble en terme d'opti, mais dautre solution que d'incorporer le merge de dept.interactive dans les fonction, sinon il n'était pas updaté par shiny
renderLeaflet({
  
  pal<-colorNumeric(palette = c("#003f5c","white","#d45087"), domain=(dept.interactive %>% extract2(input$pop_cat)))
  
  popup_info <- paste0("<strong>Departement: </strong>", 
                    dept.interactive$NOM_DEPT," - ", dept.interactive$CODE_DEPT,
                    "<br><strong>",input$pop_cat,":  </strong>",
                    trunc(sp::merge(dept.interactive, data_pop_revenus[which(data_pop_revenus$annee==input$annee_sel),],by.x="CODE_DEPT",by.y="DEP") %>% extract2(input$pop_cat)))
  
  leaflet(data = sp::merge(dept.interactive, data_pop_revenus[which(data_pop_revenus$annee==input$annee_sel),],by.x="CODE_DEPT",by.y="DEP")) %>%
  addTiles() %>%
  addPolygons(fillColor = pal(magrittr::extract2(sp::merge(dept.interactive, data_pop_revenus[which(data_pop_revenus$annee==input$annee_sel),],by.x="CODE_DEPT",by.y="DEP"), input$pop_cat)) ,
              fillOpacity=0.8,
              color = "Black", 
              weight = 1,
              stroke = TRUE,
              popup=popup_info)
})
```

# TOP rémunération 1

Column {.sidebar}
------

```{r}
selectInput("revenu_cat2", label="Sélection de la catégorie de revenu", choices=revenus_categories)
```

Row {.tabset}
------

### Top rémunération des catégories sociales

#### Tab 1

```{r}
# top 8 des catégories socio les mieux rémunérées (en moyenne)

moyennes = data.frame(colMeans(data_revenus[c(-1,-2)])) %>%
  rename(valeur_moyenne=1) %>% arrange(desc(valeur_moyenne))
moyennes$categorie <- row.names(moyennes)
moyennes <- head(moyennes,8)

description <- merge(moyennes, labels_revenus, by.x="categorie", by.y="VAR_ID") %>%
  rename(Description=VAR_LIB_LONG) %>%
  select(-VAR_LIB) %>%
  arrange(desc(valeur_moyenne)) 
datatable(description)

```

#### Chart1

```{r}
ggplot(aes(x =reorder(categorie, -valeur_moyenne), y=valeur_moyenne), data=moyennes) + geom_bar(stat='identity', fill = c("#ffa600","#ff7c43","#f95d6a","#d45087","#a05195","#665191","#2f4b7c","#003f5c")) +
  labs(x="Catégorie sociale", y="Salaire net horaire moyen")
```

### Top des départements les mieux rémunérés

#### Tab2

```{r}
#5 départements avec salaire le plus élevé selon catégorie pop sélectionnées

renderDataTable({head(arrange(data_revenus[c("DEP", "LIBGEO", input$revenu_cat2 )],desc(.data[[input$revenu_cat2]])), 5)})

```

#### Chart 2

```{r}
#départements concerné
renderPlot({ggplot() +
  geom_polygon(data = dept.df2 %>% add_column(in_top= (dept.df2$DEP %in% extract2(head(arrange(data_revenus,desc(.data[[input$revenu_cat2]])), 5), "DEP"))), 
               aes(x = long, y = lat, group = group, fill = .data$in_top),
               color = "black") + 
  coord_map() +
  scale_fill_manual(values = c("TRUE"="#ffa600", "FALSE"="#2f4b7c")) +
  guides(fill = "none")+
  theme_void()
})
```

