---
title: "data_exploration.rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("tibble")
update.packages("ellipsis")
library(tibble)
library(dplyr)
library(DT)


pacman::p_load(DT, data.table)

data=tibble()

#read first xls file (2015)

data_j=readxl::read_xls(paste0("C:\\Users\\bapti\\Documents\\Boulot\\S7\\R\\projet\\",
                             "base-ic-evol-struct-pop-2015.xls"),sheet="IRIS", skip=5)

non_year_vars = names(data_j)[0:12]
year_vars = names(data_j)[13:length(data_j)]

#drop the characters ,nb 2 and 3 representing the year
year_vars = paste0(substring(year_vars,0,1),substring(year_vars,4))

names(data_j)=c(non_year_vars,year_vars)

#add the variable "annee"
data_j$annee=2015 
data=bind_rows(data,data_j)


#read other xlsx files (2016,2017)

for (annee in 2016:2017){
  data_i = readxl::read_xlsx(paste0("C:\\Users\\bapti\\Documents\\Boulot\\S7\\",
                                               "R\\projet\\base-ic-evol-struct-pop-",
                                               annee,".xlsx"), sheet="IRIS", skip=5)
  non_year_vars = names(data_i)[0:12]
  #drop the characters ,nb 2 and 3 representing the year
  year_vars = names(data_i)[13:length(data_i)] 
  year_vars = paste0(substring(year_vars,0,1),substring(year_vars,4))

  names(data_i)=c(non_year_vars,year_vars)
 
  data_i$annee=annee
  data=bind_rows(data,data_i)
}
```

#Données sur population et revenus par région et par année

```{r}
#[WARNING] data is skewed; population data from 2015-17 was merged with 2019 salaries
vars = colnames(data)
vars <-   vars[c(seq.int(-12,-3),-1)] #remove everything not groupable by region (=keep only pop vals + reg )


new_data= data[vars]

#group by dep, annee summing pop values
new_data <- new_data %>%
            group_by(REG,annee) %>%
            summarise_all(sum)

data_wage <- readxl::read_xlsx(paste0("C:\\Users\\bapti\\Documents\\Boulot\\S7\\R\\projet\\",
                             "base-cc-bases-tous-salaries-2019.xlsx"),sheet="REG", skip=5)
data_wage <- data_wage %>% rename(REG = CODGEO)

data_pop_wage <- merge(new_data,data_wage,by="REG")

```

```{r}
#[WARNING] data is skewed; population data from 2015-17 was merged with 2019 salaries
vars = colnames(data)
vars <-   vars[c(seq.int(-12,-4),-1)] #remove everything not groupable by region (=keep only pop vals, dep and reg )


new_data= data[vars]

#group by dep, annee summing pop values
new_data <- new_data %>%
            group_by(REG,DEP,annee) %>%
            summarise_all(sum)

data_wage <- readxl::read_xlsx(paste0("C:\\Users\\bapti\\Documents\\Boulot\\S7\\R\\projet\\",
                             "base-cc-bases-tous-salaries-2019.xlsx"),sheet="DEP", skip=5)
data_wage <- data_wage %>% rename(DEP = CODGEO)

data_pop_wage <- merge(new_data,data_wage,by="DEP")

```

